apiVersion: v1
kind: Service
metadata:
  name: legacy-app-service
  namespace: legacy-app-ns

  labels:
    app: legacy-app

spec:
  type: LoadBalancer

  selector:
    app: legacy-app

  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000